# Generated by Django 4.2.28 on 2026-02-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo URL')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, help_text='e.g., 1-10, 11-50, 51-200, 201-500, 500+', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, help_text='e.g., Engineering Manager', max_length=255, null=True)),
                ('team', models.CharField(blank=True, help_text='e.g., Platform, Mobile', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomy', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('feedback_quality', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('clarity', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('fairness', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('work_life_balance', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('duration', models.CharField(blank=True, choices=[('<3m', 'Less than 3 months'), ('3-12m', '3-12 months'), ('1-3y', '1-3 years'), ('3y+', 'More than 3 years')], max_length=20, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('would_work_again', models.CharField(blank=True, choices=[('yes', 'Yes'), ('unsure', 'Unsure'), ('no', 'No')], max_length=20, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.manager')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('other', 'Other')], default='manual', max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_contributors', models.IntegerField(default=0, verbose_name='Number of Contributors')),
                ('avg_autonomy', models.FloatField(blank=True, null=True)),
                ('avg_feedback_quality', models.FloatField(blank=True, null=True)),
                ('avg_clarity', models.FloatField(blank=True, null=True)),
                ('avg_fairness', models.FloatField(blank=True, null=True)),
                ('avg_work_life_balance', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('public_summary', models.TextField(blank=True, null=True)),
                ('top_tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('best_for', models.TextField(blank=True, null=True)),
                ('hard_for', models.TextField(blank=True, null=True)),
                ('is_publishable', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Aggregate',
                'verbose_name_plural': 'Company Aggregates',
            },
        ),
    ]
